spring:
  application:
    name: instruction-${server.port}
  datasource:
    url: jdbc:h2:./data/istr/database;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE

  jpa:
    hibernate:
      ddl-auto: update

    generate-ddl: true
server:
  port: 8080

logging:
  level:
    root: info
#    com:
#      example: debug


axon:
  axonserver:
#    ssl-enabled: true
#    cert-file: ./tls.crt
    #    servers: 192.168.221.195
    servers: 192.168.10.60

  distributed:
    enabled: true
  serializer:
    general: xstream
    messages: xstream
    events: xstream





